/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.letscode;

public class App {

    public static void main(String[] args) {

        ReadCsvFile file = new ReadCsvFile("C:\\Users\\samug\\Desktop\\letsCode\\projetosJava\\calculadoraSaldoBancario\\", "operations", "csv");
        DateOperations data = file.openCsvFile();
    }
}
